version: "3.9"

services:
    webserver:
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./wordpress:/var/www/html:delegated
    database:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress_db
            MYSQL_USER: altnic
            MYSQL_PASSWORD: secret
        volumes:
            - ./mysql-data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        environment:
            PMA_HOST: database
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8081:80"
        restart: always
    php:
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ./wordpress:/var/www/html:delegated
